Add openfeign
YaWokrshopJavaTeam/yandex-workshop-user-service pull request #4
Opened 2024-12-17 13:45 UTC by KurakinPavel

2024-12-21 11:01 UTC, druzhininyury requested changes
Огромная работа. Я попытался вникнуть в основные изменения. Мне кажется, что добавленная архитектура сервиса вместе с новым функционалом привнесла много потенциальных ошибков. Думаю, стоит обсудить.

2024-12-21 11:01 UTC, druzhininyury commented on pom.xml
> +			<version>3.1.9</version>
Нет смысла указывать версию, если подключён spring-cloud-dependencies, т.к. в нём уже все совместимые версии настроены.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
> +    @PutMapping("/internal/to-manual")
Если я правильно помню, то соглашение для PUT запроса такое: меняем данные целиком. Поэтому здесь скорее PATCH запрос.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/resources/db/migration/V2__initial_schema.sql
> +ALTER TABLE users ADD registration_type INTEGER NOT NULL;
Вкусовщина, но я бы пользовался полем `varchar` для наглядности. Так будет проще, если придется заглядывать непосредственно в базу данных. Да, при этом мы немного жертвуем скоростью и памятью, но работа с пользователями - редкое событие.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/resources/db/migration/V2__initial_schema.sql
Как я понимаю, миграция еще не настроена. Ты добавил поле в таблицу, причём оно `not null`. Но что будет с уже существующими записями? Для них это поле останется пустым.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/resources/application.properties
> +server.port=8081
Не уверен, что надо менять порт. Номер порта для нашего сервиса в целом определяется настройками докера. Поэтому внутренние порты микросервисов я бы оставил стандартными, чтобы проще было ловить ошибки.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/enums/RegistrationType.java
Это перечисление я бы переместил в пакет dto.enum или model.enum, чтобы оно было логически поближе к классами, в которых используется.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/dto/ResponseWithUserId.java
> +public class ResponseWithUserId {
Для сохранения общего стиля может стоит переименовать в UserIdDto.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/RegistrationClient.java
Вкусовщина. По мне `RegistrationClient` скорее контроллер, чем сервис. Поэтому может его стоит отправить в контроллеры или в отдельный пакет `utils`.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.MANUAL));
Здесь пользователь не сможет зарегистрироваться явно, если он был уже зарегистрирован неявно из-за нарушения уникальности поля `email`.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User availableUser = userRepository.getUserByEmail(newUserDto.getEmail());
Если запрос может вернуть пустое значение, то рекомендуется использовать Optional, чтобы явно показать читающему, что значение может быть пустое. JPA репозиторий возврат Optional<User> поддерживает.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (availableUser != null && availableUser.getId() > 0) {
Эта строчка непонятная. Если `availableUser` найден, то он ранее был добавлен и тогда у него и так `ID` положительное.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userToUpdate = userRepository.getReferenceById(userId);
Не стоит полагаться, что другой сервис отправит корректные данные. Нужна явная проверка, что `ID` существует.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userToUpdate.getRegistrationType().equals(RegistrationType.MANUAL)) {
С обновлением `email` действительно непонятно. Но зачем запрещать обновлять `name`?
Второй вопрос, а `name` в `user-service` и в `registration-service` это одна сущность? Если одна, то зачем она в регистрации? А может это псевдоним?

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            throw new AuthenticationException("Registration status of user with id=" + userId + " is already MANUAL.");
Здесь лучше в строку вместо `MANUAL` вставлять `RegistrationType.MANUAL.toString()` на случай изменения названий констант.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            responseWithUserId = registrationClient.confirmUser(authRegistrationDto.getId(), authRegistrationDto.getPassword());
Теперь `user-service` стал завязан на `registration-service`. Это добавило зависимостей. Мне кажется, что архитектура `user-service` не должна знать про другие сервисы.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userForAutoDelete = userRepository.getReferenceById(userId);
Не стоит полагаться на то, что другой сервис пришлет корректные данные.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userForAutoDelete.getRegistrationType().equals(RegistrationType.AUTO)) {
А если пользователь не удален, то стоит вернуть какой-нибудь статус ошибки.

2024-12-21 11:01 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +    public void autoDeleteUser(Long userId) {
Если я правильно понял, то может быть такая ситуация: 
- пользователь создан автоматически
- приходит обычный запрос на удаление пользователя, который не изменился.
- пользователь удаляется, `event-service` ничего об этом не знает.

2024-12-21 11:16 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
> +    @PutMapping("/internal/to-manual")
Здесь добавлю ещё комментарий:
В ревью от Марии говорилось, что можно не указывать ResponseStatus(HttpStatus.OK), тк это стандартный ответ. Так как мы всё равно будем рефакторить, то предлагаю сразу делать без них

2024-12-21 11:21 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/dto/ResponseWithUserId.java
> +public class ResponseWithUserId {
В registration service я оставляла комментарий, что, раз в DTO только одно поле, то стоит просто возвращать это поле, а не DTO. Павел с ним согласился, так что и этот класс, скорее всего, будет удалён

2024-12-21 11:29 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/service/RegistrationClient.java
Я добавляла в отдельный пакет client. Мне кажется, util не очень подходящий для этого пакет

2024-12-21 11:49 UTC, KurakinPavel commented on pom.xml
> +			<version>3.1.9</version>
Ок.

2024-12-21 11:49 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
> +    @PutMapping("/internal/to-manual")
Согласен.

2024-12-21 12:06 UTC, KurakinPavel commented on src/main/resources/db/migration/V2__initial_schema.sql
Миграция настроена, но в настоящий момент каждый запуск в наших условиях начинается с двух этапного создания новой базы данных без данных.
При модификации "боевого" приложения, в котором уже есть данные, пришлось бы прописывать логику работы новых (внесённых текущим пулл реквестом) запросов, в условиях, когда соответствующее поле не содержит данных.

Но в целом - ок, поменяю.

2024-12-21 12:07 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/enums/RegistrationType.java
Ок.

2024-12-21 12:08 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/dto/ResponseWithUserId.java
> +public class ResponseWithUserId {
Да, я планирую переделать так, чтобы между сервисами передавалось не DTO, а Integer значение.

2024-12-21 12:09 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/RegistrationClient.java
Ок.

2024-12-21 13:41 UTC, KurakinPavel commented on src/main/resources/application.properties
> +server.port=8081
Я сервисы при отладке вне докера запускал, как отдельные приложения, изменяя в application.properties строки со spring.datasource (url, username и password).
Отсюда и порты разные в сервисах остались. 

Если при доработке оставшихся задач проще стандартные значения - ок, поменяю.

2024-12-21 13:49 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.MANUAL));
Не сможет. Можно проверить, что он уже AUTO, и выбросить исключение: "Переводись в "ручную регистрацию" через (такой-то) сервис".
Так реализую, или есть другие предложения?

2024-12-21 13:54 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User availableUser = userRepository.getUserByEmail(newUserDto.getEmail());
Ок, поправлю.

2024-12-21 13:57 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (availableUser != null && availableUser.getId() > 0) {
Да, лишняя проверка.

2024-12-21 14:05 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userToUpdate = userRepository.getReferenceById(userId);
Ок, добавлю возврат Optional с необходимыми проверками.

2024-12-21 14:22 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            throw new AuthenticationException("Registration status of user with id=" + userId + " is already MANUAL.");
Скорее: ... + " is already " + RegistrationType.MANUAL)
В String Java и сама переведёт.

Исправлю.

2024-12-21 14:58 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            responseWithUserId = registrationClient.confirmUser(authRegistrationDto.getId(), authRegistrationDto.getPassword());
Здесь всё интереснее, так как у меня - ошибка. 
Юзер не может изначально знать свой id в user-service, так как его возвращение при регистрации заявки в registration-service не предусмотрено. Возвращается AuthRegistrationDto (id заявки + пароль к заявке), и указания id юзера в соответствующем хедере запроса к user-service быть не должно. 
Только найдя по данным AuthRegistrationDto id юзера в registration-service можно с ним что-то сделать в user-service (в данном случае, перевести в MANUAL).

Можно перетащить "внешний" эндпоинт для перевода юзера в состояние MANUAL из user-service в registration-service. Тогда последний будет проверять юзера по своим данным, и направлять соответствующее "указание" в user-service. 
Как-то так? Ваше мнение, коллеги.

2024-12-21 15:11 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userForAutoDelete = userRepository.getReferenceById(userId);
Ок, добавлю возврат Optional с необходимыми проверками.

2024-12-21 15:26 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userForAutoDelete.getRegistrationType().equals(RegistrationType.AUTO)) {
Нужно обсудить.
Этот эндпоинт удаляет AUTO юзера по запросу из registration-service, когда удаляется единственная заявка на участие этого юзера. 
Если user MANUAL, то его регистрация в user-service удаляться и не должна, и какая-либо ошибка тут - нецелесообразна. registration-service просто удалит "свою" сущность, и всё.

2024-12-21 15:46 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +    public void autoDeleteUser(Long userId) {
Логика такая: Пока пользователь AUTO - его id-шник на какие-либо эндпоинты поступать не должен. Он "крутиться" как внутренняя информация в базах и между user- и registration- сервисами. И только в момент перевода в MANUAL счастливому пользователю должен выдаваться его id (проверю / учту при доработке).
Соответственно, в event, task или review сервисах AUTO user ничего делать не должен / не может.

2024-12-21 16:54 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userToUpdate.getRegistrationType().equals(RegistrationType.MANUAL)) {
Тут я придерживаюсь принципа: если юзер управляется из registration-service, то и данные должны быть идентичны данным registration-service. Как только он становится MANUAL - будь добр, управляй собой через эндпоинты user-service.
При этом получается, что на мероприятия юзер может регить для себя кучу псевдонимов с новыми email-ами. Но этим все сервисы страдают, если не требуют подтверждения через что-то более стабильное, чем мейл.
Так что я бы тут ничего не менял.

2024-12-21 17:05 UTC, KurakinPavel commented on src/main/resources/db/migration/V2__initial_schema.sql
> +ALTER TABLE users ADD registration_type INTEGER NOT NULL;
EnumType.STRING? 
Ok.

2024-12-21 17:16 UTC, druzhininyury commented on src/main/resources/db/migration/V2__initial_schema.sql
Лучше избегать допущений, что что-то будет использовано определённым образом.

Изменения минимальные - добавить заполнение всех полей во вторую версии миграции:
```
UPDATE user
SET type = 0;
```

2024-12-21 17:30 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userForAutoDelete = userRepository.getReferenceById(userId);
В целом совсем красиво написать удаление сущностей в ситуации, где сущность удаляется в основном сервисе (здесь: user-service), а потом корректно удаляются данные из засимого сервиса (здесь: registration-service) без брокера сообщений невозможно.

Некрасиво писать будем совсем некрасиво: придётся запихивать в user-service удаление и из event-service (там у нас группы организаторов есть), и из task-service. Получаться спагетти.

В целом надо подумать. Моё мнение: физическое удаление - плохо, лучше иметь поле `isActive` и удаление реализовывать через запись `false` в это поле.

2024-12-21 17:36 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userForAutoDelete.getRegistrationType().equals(RegistrationType.AUTO)) {
Тогда у нас получается разный стиль: в эндпоинтах на удаление мы возвращаем ошибку, если удаляемый объект отсутствует. А тут возвращаем `OK`. ... не знаю, плохо ли это.

2024-12-21 17:38 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +    public void autoDeleteUser(Long userId) {
На __не должен__ полагаться опасно. У нас может фронтендер ошибся, а нам чинить боевую базу данных. Или злоумышленник посмотрел dto-шки и решил сервис обрушить.

2024-12-21 17:41 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/dto/ResponseWithUserId.java
> +public class ResponseWithUserId {
А правильно ли я понимаю, что технически `Integer` значение всё равно будет завернуто в json? Но с предложением Лили, у нас просто станет на один класс меньше?

2024-12-21 17:43 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.MANUAL));
Выглядит не очень user-friendly.

2024-12-21 17:47 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/service/RegistrationClient.java
> +@FeignClient(name = "registration-service-client", url = "http://localhost:8084")
Аналогично комментарию в registration service стоит поменять url

2024-12-21 17:49 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userToUpdate.getRegistrationType().equals(RegistrationType.MANUAL)) {
Мммм, запутанно. В registration service может быть дважды использован один `email`, но с разными именами. Что тогда будет хранится в user-service?

2024-12-21 17:52 UTC, KurakinPavel commented on src/main/resources/db/migration/V2__initial_schema.sql
Ок.

2024-12-21 17:54 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/dto/ResponseWithUserId.java
> +public class ResponseWithUserId {
@druzhininyury, по сути да. По моему мнению: нет смысла делать много DTO, которые возвращают только одно поле. Если бы это был реальный проект, то приложение могло бы разрастаться в будущем, DTO становилось бы больше, и это просто мешало бы разобраться.

2024-12-21 18:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +    public void autoDeleteUser(Long userId) {
Предлагаю вернуться к вопросу при изучении / внедрении / экспериментах со Spring Security.
Сейчас эту проблему можно решить только за счёт натыкивания запросов в user-service / проверок "а не AUTO ли он", и соответствующих исключений во все другие микросервисы.
Но так точно делать не надо.

2024-12-21 18:06 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userForAutoDelete.getRegistrationType().equals(RegistrationType.AUTO)) {
Registration service и вернёт. А юзер и не просил регить его в како-то другом сервисе.
Всё это - скорее вопрос к ТЗ, чем к реализации.

2024-12-21 18:08 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.MANUAL));
В теории, если говорить про user-friendly, то омжно было бы сделать что-то такое: пользователь жмёт зарегистрироваться -> ему высвечивается "Подавали ли вы заявку на участие в мероприятии" -> если да, то переводим на эндпоинт с переводом user в manual; если нет, то на этот

2024-12-21 18:11 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userForAutoDelete = userRepository.getReferenceById(userId);
На текущий момент предлагаю оставить имеющуюся реализацию.

2024-12-21 18:12 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +    public void autoDeleteUser(Long userId) {
Надо подумать. Но Spring Security не защитит нас от наших же ошибок.

2024-12-21 18:23 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.MANUAL));
Не user-friendly, но иначе не сделаешь. Для перевода в MANUAL в такой ситуации юзеру нужны данные его регистрации на мероприятие, и возможно, вообще обращение в другой сервис.

Такие переводы возможны в фронтенд приложении.

2024-12-21 18:33 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userForAutoDelete.getRegistrationType().equals(RegistrationType.AUTO)) {
Тут соглашусь с Павлом, так как это такая логика работы registration service. И лично у меня нет идей как это исправить в нашем случае, кроме как запрещать пользователю регистрироваться вручную в приложении пока у него есть заявки на мероприятия, но это слишком не user-friendly

2024-12-21 18:38 UTC, Hyacintholuscus commented on src/main/resources/db/migration/V2__initial_schema.sql
Соглашусь с Юрием. Хоть это и учебный проект, стоит обращать внимание на это, чтобы случайно не сломать уже боевой проект. Так же лучше было бы сначала добавить само поле registration_type  без ограничения NOT NULL, затем обновить у уже существующих значение, а потом добавлять ограничение. Мне кажется, так будет корректнее

2024-12-21 18:38 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userToUpdate.getRegistrationType().equals(RegistrationType.MANUAL)) {
В user-service - name первого обращения. Или name, пришедший с каким-либо обновлением через registration-service. Но name для user-service для AUTO юзера - просто "заглушка". Там имеет значение пара id + email.

2024-12-21 18:43 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +    public void autoDeleteUser(Long userId) {
Или от странностей ТЗ.
Сама идея "анонимной" регистрации на мероприятия - неправильна.

2024-12-22 04:37 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userToUpdate = userRepository.getReferenceById(userId);
@druzhininyury, метод getReferenceById в - стандартный для JpaRepository. Если я всё правильно поняла, то суть в том, что, в отличие от обычного findById он делает обращение в БД не сразу, а в момент взаимодействия с полученными данными (по сути lazy). Плюс такого подхода в том, что при операциях изменения существующей сущности вместо 2 обращений в БД (SELECT и INSERT идёт только одно обращение INSERT). Если сущность не существует, то пробрасывается стандартное исключение DataIntegrityViolationException. Вот статья: https://www.baeldung.com/spring-data-jpa-getreferencebyid-findbyid-methods

2024-12-24 17:24 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
> +    @PutMapping("/internal/to-manual")
Эндпоинт "переехал" в createUser.

2024-12-24 17:44 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/dto/ResponseWithUserId.java
> +public class ResponseWithUserId {
Теперь не требуется ни ДТО, ни Integer.

2024-12-24 17:45 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/RegistrationClient.java
Клиент не требуется.

2024-12-24 17:49 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.MANUAL));
В эндпоинт добавлена логика перевода из AUTO в MANUAL

2024-12-24 17:54 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userToUpdate = userRepository.getReferenceById(userId);
Изменил все "внутренние" эндпоинты так, чтобы они вообще не выбрасывали исключений.
Скорее всего, до юзеров, которые работают с registration-service, не нужно доводить инфо о манипуляциях с их данными в user-service.

2024-12-24 17:57 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userToUpdate.getRegistrationType().equals(RegistrationType.MANUAL)) {
Из данных, получаемых из registration-service, в user-service теперь приходит только email. Остальное - заглушки.  Кроме того, email обновляется при обновлении данных в registration-service

2024-12-24 17:59 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            responseWithUserId = registrationClient.confirmUser(authRegistrationDto.getId(), authRegistrationDto.getPassword());
Функционал метода переехал в стандартный createUser

2024-12-24 18:01 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        User userForAutoDelete = userRepository.getReferenceById(userId);
Реализацию изменил, чтобы не было исключений.
Юзер удаляется только если найден.

2024-12-24 18:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        if (userForAutoDelete.getRegistrationType().equals(RegistrationType.AUTO)) {
Реализацию изменил, чтобы не было исключений.
Юзер удаляется только если найден.

2024-12-24 18:39 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/RegistrationClient.java
> +@FeignClient(name = "registration-service-client", url = "http://localhost:8084")
Клиент удалён из реализации.

2024-12-24 18:42 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            throw new AuthenticationException("Registration status of user with id=" + userId + " is already MANUAL.");
Реализация изменена, и необходимость информирования юзеров о манипуляциях с AUTO / MANUAL больше не предусматривается.

2024-12-25 19:15 UTC, druzhininyury approved these changes
Отличная работа!

Одобрил, но всё же загляни. в `UserServiceImpl`.

На тесты не смотрел. Без выработки ТЗ

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
> +    public Long autoCreateUser(@RequestBody NewUserDto newUserDto) {
Вкусовщина. Мне почему-то хочется назвать метод более явно, что вроде getUserOrElseCreateAndGet.

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
>      public void autoDeleteUser(@RequestHeader("X-User-Id") Long userId) {
Вкусовщина: мне в своё время Лиля сказала, что здесь идет доступ к ресурсу `User`, соответственно, более канонично передавать `id` через переменную пути: `/users/{userId}/internal`

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
>      @ResponseStatus(HttpStatus.CREATED)
Интересно, а если запрос и читает и создает, то какой код ответа нужен? :)

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        Optional<User> availableUser = userRepository.getUserByEmail(newUserDto.getEmail());
При рефакторинге я бы сделал метод в репозитории `getUserByEmailAndRegistrationTyp`, чтобы переложить часть логики на базу данных.

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            User userTransferredToManual = userRepository.save(userMapper
Здесь вызов метод `save` необязателен, т.к. Hibernate сам это сделает при завершении текущего метода.

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
>          User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.AUTO));
Возможно авто-пользователю стоит сохранять только почту, остальными полями мы просто не пользуемся. 

Плюс, будущего разработчика других сервисов может запутать наличие разных полей в `NewUserDto`.

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            User updatedUser = userRepository.save(userMapper.autoUpdateUser(userToUpdate.get(), updateUserFromRegistrationDto));
Вижу здесь потенциальную проблему: пусть пользователь сделал две регистрации с разными почтами: `box1@mail.ru` и `box2@mail.ru`. Затем, во второй регистрации он хочет обновить почту на `box1@mail.ru`.

Сейчас пользователь сделать этого не сможет и не сможет понять по какой причине.

Какая должна быть логика? Возможно, удалить пользователя с почтой `box2@mail.ru`, но что тогда делать с его `id` в БД микросервиса `registration-service`.

2024-12-25 19:15 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
Методы `getUser` и `getUsers` теперь возвращают и авто-пользователей. Скорее всего это не то, что ожидает фронэнд.

2024-12-25 19:15 UTC, druzhininyury commented on src/main/resources/db/migration/V2__initial_schema.sql
> +ALTER TABLE users ADD registration_type VARCHAR(20);
Можно добавить `NOT NULL` для дополнительной защиты.

2024-12-25 19:28 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
> +    public Long autoCreateUser(@RequestBody NewUserDto newUserDto) {
Скорее createUserOrGetId.

2024-12-25 19:30 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
>      public void autoDeleteUser(@RequestHeader("X-User-Id") Long userId) {
Вкусовщина, но данные юзера - вещь конфиденциальная. Я бы их в "открытой" части не передавал.

2024-12-25 19:31 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
>      @ResponseStatus(HttpStatus.CREATED)
50/50, но по смыслу всё же ближе к CREATED.

2024-12-25 19:37 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +        Optional<User> availableUser = userRepository.getUserByEmail(newUserDto.getEmail());
Да, так будет лучше.

2024-12-25 19:37 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            User userTransferredToManual = userRepository.save(userMapper
Ок.

2024-12-25 19:40 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
>          User newUser = userRepository.save(userMapper.toUser(newUserDto, RegistrationType.AUTO));
NewUserDto для AUTO юзеров заполняются в registration-service, и там из значащих полей - только email и есть. Остальное - "заглушки", но пустыми они быть не могут.

2024-12-25 19:47 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
> +            User updatedUser = userRepository.save(userMapper.autoUpdateUser(userToUpdate.get(), updateUserFromRegistrationDto));
Согласен, надо подумать.

2024-12-25 19:51 UTC, KurakinPavel commented on src/main/resources/db/migration/V2__initial_schema.sql
> +ALTER TABLE users ADD registration_type VARCHAR(20);
Ок.

2024-12-25 19:55 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/service/UserServiceImpl.java
Если считать, что это админские эндпоинты, то так и должно быть.
Если не админские - надо подумать

2024-12-25 22:17 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
>      public void autoDeleteUser(@RequestHeader("X-User-Id") Long userId) {
Безотносительно темы комментария: в http запросе нет никаких скрытых частей, он целиком виден всем или целиком зашифрован и виден только отправителю и получателю.

2024-12-26 16:47 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
>      public void autoDeleteUser(@RequestHeader("X-User-Id") Long userId) {
url - кешируется, а заголовки - нет.
Возможно, из-за этого и в курсе User-Id практически во всех ТЗ передавался в заголовках.
Так что пусть там и остаётся.

2024-12-26 18:16 UTC, merged

2024-12-27 07:04 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/userservice/controller/UserController.java
>      public void autoDeleteUser(@RequestHeader("X-User-Id") Long userId) {
Мне кажется, что для запроса нельзя применить слово _кешируется_. Кешировать можно ответ, т.е. сохранить его в памяти, чтобы не отправлять повторный запрос. При этом нам надо сохранить информацию о запросе, чтобы понимать повторный он или нет. И тогда могут остаться все части запроса, и url, и эндпоинт, и заголовки, и тело.

Поскольку мы не управляем клиентом, то он может кешировать всё что захочет и на сколько захочет.

Вроде, HTTP запрос это проста строка текста, которая условно разделена на части. Нет никаких жестких механизмов, привязанных к этим частям. Поэтому нет у одной части запроса преимущества над другой ни в каком смысле.

Ещё не ясно, почему `id` пользователя является конфиденцальной информацией?